name: sky-hero
base: core22
version: '1.0'
summary: "Become a sky hero! Jump, dash and defeat foes on your path to glory."
description: |
  Sky Hero is a fast-paced platformer that trains you in jumping,
  dashing and attacking. Defeat enemies on every level, enjoy
  atmospheric music and unlock new stages. The road to heroism lies
  ahead — only you can conquer it!

grade: stable
confinement: strict

apps:
  sky-hero:
    command: bin/game
    plugs:
      - desktop
      - x11
      - wayland
      - unity7
      - opengl
      - home
      - audio-playback
    environment:
      SDL_AUDIODRIVER: "pulse,dummy"
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/../pulse/native"

parts:
  sky-hero:
    plugin: python
    source: .
    python-packages:
      - pyinstaller
      - pygame
    build-packages:
      - gcc
      - libc6-dev
    stage-packages:
      - libasound2
      - libpulse0       # ← ЭТО ДЛЯ pulseaudio
      - libglib2.0-0
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libx11-6
      - libpulse-mainloop-glib0


    override-build: |
      snapcraftctl build
      pyinstaller game.spec
      install -Dm755 dist/game $SNAPCRAFT_PART_INSTALL/bin/game

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio